const data = [   
{   'description': [   ' Entrance accessible ',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Anthropolgie'},
{   'description': [   ' No button to enter/exit',
' Store interior accessible'],
'stars': 3,
'title': 'Aphrodite'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Aritzia'},
{   'description': [   ' Entrance accessible',
' Bottom floor store interior accessible',
' Change room accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Atmosphere'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Azadi'},
{   'description': [   '  Entrance accessible',
'  No exit button',
'  Store interior mostly accessible',
'  Change room accessible'],
'stars': 4,
'title': 'Banana Republic'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bath and Body Works'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Beauty Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Beauty Clinic'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bell'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Blank Line Studio'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Blink Blank'},
{   'description': [   '  No button to enter/exit',
'  Store interior mostly accessible'],
'stars': 3,
'title': 'The Body Shop'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Browns'},
{   'description': [   '  No button to enter/exit',
'  Store interior mostly accessible',
'  Change room not accessible'],
'stars': 2,
'title': 'Change'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Dar Optical'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Donato'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Frank & Oak'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Freedom Mobile'},
{   'description': [   '  Entrance accessible',
'  Bottom floor store interior accessiblility',
'  Emergency exit'],
'stars': 3,
'title': '#Home'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Jill Yoga'},
{   'description': [   '  No button to enter/exit',
'  Store interior accessible'],
'stars': 3,
'title': 'Lenscrafters'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Lindt'},
{   'description': [   '  No button to enter/exit',
'  Store interior accessible',
'  Change room accessible'],
'stars': 3,
'title': 'M'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Magenta Photo'},
{   'description': [   '  No button to enter/exit',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Michael Kors'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'New Balance'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Night and Day Window'},
{   'description': [   '  No button to enter/exit',
'  Store interior accessible',
'  Change room accessible'],
'stars': 3,
'title': 'North Boys'},
{   'description': [   '  No button to enter/exit',
'  Store interior accessible',
' Change room not accessible'],
'stars': 2,
'title': 'Oak & Fort'},
{   'description': [   '  No button to enter/exit',
'  Store interior accessible',
'  Change room accessible'],
'stars': 3,
'title': 'Okaidi'},
{   'description': [   '  No button to enter/exit',
'  Store interior accessible'],
'stars': 3,
'title': 'Pandora'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Rogers'},
{   'description': [   '  Entrance accessible',
'  Change room partially accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Roots'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Royal Lepage'},
{   'description': [   '  No button to enter/exit',
'  Store interior mostly accessible'],
'stars': 2,
'title': 'Salomon'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Soft Moc'},
{   'description': [   '  Entrance accessible',
'  Low store interior accessiblility',
'  Emergency exit'],
'stars': 2,
'title': 'Structube'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Ten Spot'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Yellowkorner'},
{   'description': [   '  No button to enter/exit',
'  Store interior accessible '],
'stars': 3,
'title': 'Your Good Health'}]
