const data = [   
    {   'description': [   ' Entrance accessible ',
                           ' Store interior  accessible',
                           ' Change room accessible',
                           ' Emergency exit'],
        'stars': 3,
        'title': 'Ardene'},
    {   'description': [   ' Entrance accessible',
                           ' Side entrance not accessible',
                           ' Bathrooms not accessible',
                           ' Store interior mostly accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Barric Fiesta'},
    {   'description': [   ' Entrance not accessible',
                           ' Store interior accessible',
                           ' No emergency exit'],
        'stars': 3,
        'title': "Bill's Farm"},
    {   'description': [   ' Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Cell Rox'},
    {   'description': [   ' Entrance not accessible',
                           ' Store interior accessible',
                           ' No emergency exit'],
        'stars': 3,
        'title': 'Chunky Chicken'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Checkout area not accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Dollarama'},
    {   'description': [   ' Entrance not accessible',
                           '  Store interior not accessible',
                           '  No emergency exit'],
        'stars': 0,
        'title': 'East York Medical Health Centre'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Eye examination room not accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'East York Vision Centre'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior not accessible',
                           '  No emergency exit'],
        'stars': 0,
        'title': 'Eastern Gifts and Boutique'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change rooms not accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Fashions'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Bathroom not accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Fitness 4 Less'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Brooks Brothers'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Fly Time Travel'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  In-store entrance not accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Food Basics'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Freedom Mobile'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'H&R Block'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Hair Cici'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior not accessible',
                           '  No emergency exit'],
        'stars': 0,
        'title': 'Halal Meat'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Eye examination room not accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'i-Life Style'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Change room not accessible',
                           '  Emergency exit'],
        'stars': 2,
        'title': 'IN STYLE'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Kandahar Kabab'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Kitchen Food Fair Convenience'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Emergency exit'],
        'stars': 2,
        'title': 'Kychenx'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'LCBO'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Change room not accessible',
                           '  Emergency exit'],
        'stars': 2,
        'title': 'Lebaas 4 all'},
    {   'description': [   '  Entrance not accessible',
                           '  Side entrance accessible',
                           '  Store interior partially accessible',
                           '  No emergency exit'],
        'stars': 0,
        'title': 'Maximum Deals'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior accessible',
                           '  Change room not accessible',
                           '  No emergency exit'],
        'stars': 3,
        'title': 'Mayar'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior partially accessible',
                           '  No emergency exit'],
        'stars': 1,
        'title': 'Money Mart'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior not accessible',
                           '  No emergency exit'],
        'stars': 0,
        'title': 'Multi Accessories'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior not accessible',
                           '  No emergency exit'],
        'stars': 0,
        'title': 'Nifties Fashion'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Optical Factory'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior accessible',
                           '  Bathroom not accessible',
                           '  No emergency exit'],
        'stars': 2,
        'title': 'Pizza Pizza'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Rogers'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Scotiabank'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Change room not accessible',
                           '  Emergency exit'],
        'stars': 2,
        'title': 'Sitara'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Smokers Dream'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Spaville'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Techspot'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior not accessible',
                           '  No emergency exit'],
        'stars': 0,
        'title': 'Thorncliffe Dental Centre'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior not accessible',
                           '  No emergency exit'],
        'stars': 0,
        'title': 'Thorncliffe Shoe Repair'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior partially accessible',
                           '  No emergency exit'],
        'stars': 1,
        'title': 'The Rug Palace'},
    {   'description': [   '  Entrance accessible',
                           '  Side entrance not accessible',
                           '  Store interior mostly accessible',
                           '  Bathrooms not accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Tim Hortons'},
    {   'description': [   '  Entrance not accessible',
                           '  Side entrance not accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 1,
        'title': 'Toronto Healthcare Rehab Centre'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior partially accessible',
                           '  Emergency exit'],
        'stars': 3,
        'title': 'Value Mobile'}]