const data = [   
    {   'description': [   ' Entrance accessible ',
                           ' Store interior  accessible',
                           ' Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'A|X'},
    {   'description': [   ' Entrance accessible',
                           ' Store interior accessible',
                           ' Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Abercrombie + Fitch'},
    {   'description': [   ' Entrance accessible',
                           ' Store interior mostly accessible',
                           ' No emergency exit'],
        'stars': 4,
        'title': 'Adidas'},
    {   'description': [   ' Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Aerie'},
    {   'description': [   ' Entrance accessible',
                           ' Store interior accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Aespo'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'ALDO'},
    {   'description': [   ' Entrance accessible',
                           '  Store interior mostly accessible',
                           ' Change room accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'AllSaints'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           ' Change room accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'American Eagle'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room not accessible',
                           ' Emergency exit'],
        'stars': 4,
        'title': 'Ann Taylor'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Apple'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Aritzia'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Aveda'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'B2'},
    {   'description': [   '  Entrance accessible',
                           '  Parts of store interior accessible',
                           '  Emergency exit',
                           '  Change room not accessible '],
        'stars': 2,
        'title': 'Babaton'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Bailey Nelson'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Banana Republic Men'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 4,
        'title': 'Banana Republic Women'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Bath and Body Works'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior  accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Bell'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior not very accessible',
                           '  No emergency exit'],
        'stars': 1,
        'title': 'Bentley'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit',
                           ' Change room accessible'],
        'stars': 4,
        'title': 'Bikini Village'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           ' Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Blue Marine & Co '},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Bonlook'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Boss'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Browns'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Calendar Club'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Calforex Currency Exchange'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' No emergency exit'],
        'stars': 4,
        'title': 'Call It Spring'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Caryl Baker Visage'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Cell On'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': "Claire's"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Champs'},
    {   'description': [   '  Entrance accessible',
                           '  Most of store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Club Monaco'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Danier'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Disney'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           '  No emergency exit'],
        'stars': 2,
        'title': 'Dynamite'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'EB X'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'ECCO'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room not accessible',
                           ' No emergency exit'],
        'stars': 4,
        'title': 'Eddie Bauer'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'European Boutique'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': ' Ever New'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Fido'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Footaction'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Foot Locker'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Foreign Exchange'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Fossil'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Frank and Oak '},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Free People'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change rooms accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Gap/Gap Kids'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change rooms accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Garage'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Geox Respira'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  No emergency exit'],
        'stars': 3,
        'title': 'GNC'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Guess'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           '  Change room accessible',
                           ' No emergency exit',
                           ' Elevator in store'],
        'stars': 3,
        'title': 'H&M'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 2,
        'title': 'Haight Ashbury'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 3,
        'title': 'Hollister'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Honey'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           ' No emergency exit'],
        'stars': 4,
        'title': 'Hot Topic'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': "Hudson's Bay"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit',
                           '  Elevator in store'],
        'stars': 5,
        'title': 'Indigo'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Innesfree'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Jack and Jones'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': "Jay's Store"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Johnston & Murphy'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior not accessible '],
        'stars': 0,
        'title': 'Just Cozy'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room not accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Kate Spade'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Kicks Lounge'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': "Kiehl's"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Koodo Mobile'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior somewhat accessible',
                           '  No emergency exit'],
        'stars': 2,
        'title': 'LACO SAC'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Lacoste'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'La Senza'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Laline'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': "L'Attitudes"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Le Chateau'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Lense Crafters'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': "Levi's"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Lids'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Links of London'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           '  No emergency exit'],
        'stars': 3,
        'title': "L'Intervale"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Little Burgundy'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': "L'Occitane"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Loft'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Lululemon'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Lush'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'MAC'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' No emergency exit'],
        'stars': 5,
        'title': 'Marciano'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 5,
        'title': 'M Boutique'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 5,
        'title': 'Michael Kors'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' No emergency exit'],
        'stars': 4,
        'title': 'Microsoft'},
    {   'description': [   '  Entrance not accessible',
                           '  Store interior somewhat accessible',
                           '  No emergency exit'],
        'stars': 2,
        'title': 'Miniso'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Mobile Snap'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           '  No emergency exit'],
        'stars': 3,
        'title': 'Nature Collection'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Nike'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Nordstrom'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior not very accessible',
                           '  No emergency exit'],
        'stars': 2,
        'title': 'Nordstrom Ebar'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'NYX'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Oak + Fort'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Oakley'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': "October's Very Own"},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Old Navy'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Pandora'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Paragon'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Peoples'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Pink'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Reiss'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Rietmanz'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Rogers'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Emergency exit',
                           '  Elevator in store'],
        'stars': 4,
        'title': 'Roots'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Rudsak'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'RW&Co'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Saje'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Saks Fifth Avenue'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           ' Emergency exit'],
        'stars': 5,
        'title': 'Sandro '},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Scotch & Soda'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Sephora'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Shoo'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Shoppers Drug Mart'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Sketchers'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  No emergency exit'],
        'stars': 3,
        'title': 'Soft Moc'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'SOIA&KYO'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior not very accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 1,
        'title': 'Sport Check'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Steve Madden'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Stuart Weitzman'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Sunglasses Hut'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Swarovski'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Swatch'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'T Booth Wireless'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'TD ATM'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Telus'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'The Body Shop'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'The Canadian Naturalist'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'The Great American Backub'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           '  No emergency exit'],
        'stars': 3,
        'title': 'The Nutrition House'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'The Source'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           ' Change room accessible',
                           '   Emergency exit'],
        'stars': 5,
        'title': ' Thomas Sobo'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'TNA'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Torrid'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'TOYS TOYS TOYS'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Trade Secrets'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior not very accessible',
                           '  Emergency exit'],
        'stars': 2,
        'title': 'Trattoria Mercatto'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room not accessible',
                           ' Emergency exit'],
        'stars': 3,
        'title': 'True Religion'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Tumi'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Under Armour'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           '  Change room accessible',
                           '  No emergency exit'],
        'stars': 3,
        'title': 'Urban Planet'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior mostly accessible',
                           '  Change room accessible',
                           '  Emergency exit'],
        'stars': 4,
        'title': 'Uniqlo'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'UNO de 50'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Virgin Mobile'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  Emergency exit'],
        'stars': 5,
        'title': 'Wilfred'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           '  Emergency exit'],
        'stars': 2,
        'title': 'William - Sonoma'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Wirelesswave'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Yves Rocher France'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior somewhat accessible',
                           ' Change room not accessible',
                           '  Emergency exit'],
        'stars': 2,
        'title': 'Zara'},
    {   'description': [   '  Entrance accessible',
                           '  Store interior accessible',
                           '  No emergency exit'],
        'stars': 4,
        'title': 'Zumiez'}]
