const data = [   
{   'description': [   ' Entrance accessible ',
' Store interior  accessible',
' Emergency exit',
' Kiosk'],
'stars': 5,
'title': 'Adore Jewelry Boutique'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Aldo'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Apple'},
{   'description': [   ' Entrance accessible',
'  Store interior partially accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Aritzia'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': "The Barber's Chair"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Baskin Robbins'},
{   'description': [   ' Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bath and Body Works'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Batteries and Gadjets'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bell'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Bikini Village'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Birks'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Body Shop'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bonlook'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Browns'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Call It Spring'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Calvin klein'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Caryl Baker Visage'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Champs Sports'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': "Children's Place"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Cineplex'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Cinnabon'},
{   'description': [   '  Entrance accessible',
'  Store interior not accessible',
'  Emergency exit'],
'stars': 1,
'title': "Claire's Boutique"},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Club Monaco'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Coles'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Colours Creative Art'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': "David's Tea"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'De Barardinis'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Dental Office'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Dynamite'},
{   'description': [   '  Entrance not accessible',
'  Store interior mostly accessible',
'  No emergency exit'],
'stars': 4,
'title': 'EB Games'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Change room partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Eddie Bauer'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Eyez Optical'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fairview Mall Dental Centre'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fairview Shoe Repair'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fairview Shoe Repair'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fido'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Flight Centre'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Flower Accents'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Food Court'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Foot Locker'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Footaction'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Freedom Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Gap/Gap Kids/Baby Gap'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Gateway Newsstands'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Gatsby Studio Salon and Spa'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'GNC'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Godiva Chocolatier '},
{   'description': [   '  Outdoor entrance not accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Heart Sushi'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room partially accessible',
'  Emergency exit'],
'stars': 4,
'title': "Hudson's Bay"},
{   'description': [   '  Entrance accessible',
'  Store interior not accessible',
'  Change rooms accessible',
'  Emergency exit'],
'stars': 3,
'title': 'H&M'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Hollister'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Journeys'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Kiddie Kobbler'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Kids Foot Locker'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Kiosk'],
'stars': 5,
'title': 'Koodo'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Change room partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'La Senza'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'La Vie en Rose'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Laco Sac'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Laline'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Laura'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'LCBO'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Le ChÃ¢teau'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lego'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lens Crafters'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lids'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lâ\x80\x99intervalle'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Little Burgundy'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lâ\x80\x99Occitane'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lululemon'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lush'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'M Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'MAC'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Kiosk'],
'stars': 5,
'title': 'Macâ\x80\x99s Sushi'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Marciano'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Melanie Lyne'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Michael Hill'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Michelâ\x80\x99s Bakery CafÃ©'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'Mobile Snap'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Mountain Warehouse'},
{   'description': [   '  Outside entrance not accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Moxieâ\x80\x99s Grill & Bar'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Natural Solutions'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Nature Collection'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'NIKE'},
{   'description': [   '  Entrance accessible',
'  Store interior partialy accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Norma Reed'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'NYX'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Old Navy'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Pablo Cheesetart'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Pandora'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Peoples Jewellers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Purdys Chocolatier'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Quilts Etc'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Real Fruit Bubble Tea'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Rogers Wireless'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Roots'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'RBC'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'RW & CO'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'SAJE'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Sephora'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Sheffield Express'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Shoppers Drug Mart'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Showcase'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Skechers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Sleep Country'},
{   'description': [   '  Entrance accessible',
'  Store interior not accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Sport Check'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Steve Madden'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Strauss Menâ\x80\x99s Wear'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Sunglass Hut'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Sunshine Spa & Nails'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Suzy Shier'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Swarovski'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'T Booth Wireless'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'TD Canada Trust'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Telus Mobility'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Ten Renâ\x80\x99s Tea '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Source'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change rooms partially accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Tommy Hilfiger'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Tonyc Salon & Spa'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Toys Toys Toys'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Trade Secrets'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Urban Behaviour'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Urban Planet'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Victoriaâ\x80\x99s Secret'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Virgin Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'West 49'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Zara'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Zumiez'}]
