const data = [   
{   'description': [   ' Entrance accessible ',
' Store interior is mostly  accessible',
' Emergency exit'],
'stars': 4,
'title': 'Aldo'},
{   'description': [   ' Entrance accessible',
' Store interior is mostly accessible',
' Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Alia N Tanjay'},
{   'description': [   ' Entrance accessible',
' Store interior is accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Alyani'},
{   'description': [   ' Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'American Eagle Outfitters'},
{   'description': [   ' Entrance not accessible',
' Store interior is mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Aritzia'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Bath and Body Works'},
{   'description': [   ' Entrance accessible',
' Interior is partly accessible',
' Change rooms not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Beautiful Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bedo'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bell'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': " Bella's Shoes"},
{   'description': [   '  Entrance accessible',
'  Store is barely accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Bonkers'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Boutique X'},
{   'description': [   '  (3.5) ',
'  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Browns'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bzz-E-Kids Indoor Playground & Multi-Sport Gym'},
{   'description': [   '  (2.5) ',
'  Entrance accessible',
'  Store interior is partly accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Carlton Cards'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Caryl Baker Visage'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Cavallino'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'CellRox'},
{   'description': [   '  (4.5)',
'  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Change Lingerie'},
{   'description': [   '  Entrance accessible',
'  Store interior is partly accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': "Children's Place"},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': "Clarie's Boutique"},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Club Monaco'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Cradle & Co'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'CSO: Canadian Shoe Outlet'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Curio Hair & Body'},
{   'description': [   '  Entrance is accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 4,
'title': 'DAVIDs Tea'},
{   'description': [   '  Entrance is accessible',
'  Store interior is mostly accessible',
'  Change Room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Designer Row'},
{   'description': [   '  Entrance is accessible',
'  Store interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Dollorama'},
{   'description': [   '  (4.5)',
'  Entrance accessible',
'  Store interior is mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Dynamite'},
{   'description': [   '  Entrance  accessible',
'  Store interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'EB Games'},
{   'description': [   '  Entrance accessible',
'  Store interior is partly accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Emmanuel Bitini'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Experimax'},
{   'description': [   '  (2.5)',
'  Entrance accessible',
'  Store interior is barely accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Femme De Carriere'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fido'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Foot Locker'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Freedom Mobile'},
{   'description': [   '  (4.5) ',
'  Entrance accessible',
'  Store interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Fruit of the Land'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Gap/Gap kids/Baby Gap'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Garage Clothing Co.'},
{   'description': [   '  Some corners are too narrow',
'  Store interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'GNC-General Nutrition Care'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'H&M'},
{   'description': [   '  Entrance accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'H & R Block'},
{   'description': [   '  Entrance  accessible',
'  Store Interior partly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Honey'},
{   'description': [   ' (4.5)',
'  First Entrance accessible',
'  Second entrance is not accessible',
'  Store interior is accessible',
'  Emergency exit'],
'stars': 4,
'title': 'HOTBOX'},
{   'description': [   ' (3.5)',
'  Entrance accessible',
'  Store Interior is partly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Justice'},
{   'description': [   '  Entrance accessible',
'  Store Interior is mostly accessible',
'  Change room  accessible',
'  Emergency exit'],
'stars': 4,
'title': 'K. Barketti'},
{   'description': [   '  Entrance accessible',
'  Store Interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'K Jamson'},
{   'description': [   '  Entrance accessible',
'  Store Interior is partly accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Koal & Co'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': "L'Attitudes"},
{   'description': [   '  Entrance accessible',
'  Store Interior is party accessible',
'  Chsnge room not accessible',
'  Emergency exit'],
'stars': 3,
'title': 'La Vie En Rose'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Larua,Laura Petites,Laura Plus'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 4,
'title': "Le Chateau Men's"},
{   'description': [   '  Entrance accessible',
'  Store Interior is  barely accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': "Le Chateau Women's"},
{   'description': [   ' (4.5)',
'  Entrance accessible',
'  Store Interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Lenscrafters'},
{   'description': [   ' (3.5)',
'  Entrance accessible',
'  Store Interior is partly accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 3,
'title': 'M Boutique'},
{   'description': [   '  Entrance accessible',
'  Store Interior is  accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Melanie Lyne'},
{   'description': [   '  Entrance accessible',
'  Store Interior is  accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Melonhead'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Miniso'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Mobilinq'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Moments Watches & Jewelry'},
{   'description': [   '  Entrance accessible',
'  Store Interior is partly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Moshe Fine Jewelry'},
{   'description': [   '  Entrance accessible',
'  Spa is accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Natural Solutions'},
{   'description': [   ' (4.5)',
'  Entrance accessible',
'  Store Interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Nature Solutions'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'New Life'},
{   'description': [   '  Entrance accessible',
'  Store Interior is partly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Nortown Foods'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'NYC Footwear and Clothing'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Nygard'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Old Navy'},
{   'description': [   '  Entrance accessible',
'  Store Interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Pandora'},
{   'description': [   '  Entrance accessible',
'  Store Interior is partly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Posh'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Promenade Travel'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'REXALL'},
{   'description': [   ' (4.5)',
'  Entrance accessible',
'  Store Interior is mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Rinascimento'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Rogers Wireless'},
{   'description': [   '  Entrance accessible',
'  Store Interior is mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Roots'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Royal Luxury Bedding'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'SGH Suglasses Hut'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Showcase'},
{   'description': [   ' (4.5)',
'  Entrance accessible',
'  Store Interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Shumaker'},
{   'description': [   ' (4.5)',
'  Entrance accessible',
'  Store Interior is mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Sox City'},
{   'description': [   ' (2.5)',
'  Entrance accessible',
'  Store Interior is barely accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Sport Chek'},
{   'description': [   '  Entrance accessible',
'  Store Interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Stich It'},
{   'description': [   '  Entrance accessible',
'  Store Interior is mostly accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Suzy Shier'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Swarovski'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'T & T Supermarket'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'T Booth Wireless'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Trade Secrets & The Cut Above'},
{   'description': [   '  Entrance accessible',
'  Store Interior is  partly accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Tristan'},
{   'description': [   '  Entrance accessible',
'  Store Interior is mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Urban Kids'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Urban Planet/ West 49'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Walking on a Cloud'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Watch & Clock World Inc.'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Waxed Wax Bar'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Wireless Wave'},
{   'description': [   '  Entrance accessible',
'  Store Interior is accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Zephaniah'},
{   'description': [   '  Entrance accessible',
'  Middle aisles too narrow',
'  Accessible change room'],
'stars': 5,
'title': "Zoe's Fashion"}]