const data = [   
{   'description': [   ' Entrance accessible ',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 3,
'title': 'Aldo'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 3,
'title': 'Aldo Accessories '},
{   'description': [   ' Entrance accessible',
' Store interior not very accessible',
' Change room mostly accessible',
' Emergency exit'],
'stars': 2,
'title': 'Ardene '},
{   'description': [   ' Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Aritzia '},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'AtEaze'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bath and Body Works'},
{   'description': [   ' Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bell'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bentley '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Bitter Sweet '},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bluenotes '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'BONLOOK '},
{   'description': [   '  Entrance accessible',
'  Store interior not very accessible',
'  Change room mostly accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Broadway Fashion '},
{   'description': [   '  Entrance accessible',
'  Store interior not very accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Browns'},
{   'description': [   '  Entrance not accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Call It Spring'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Calvin Klein '},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Claireâ\x80\x99s '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Disney Store'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Dollarama'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Dynamite '},
{   'description': [   '  Entrance accessible',
'  Store interior not very accessible',
'  Emergency exit'],
'stars': 2,
'title': 'EB Games'},
{   'description': [   '  Entrance accessible',
'  Store interior not accessible',
'  Emergency exit'],
'stars': 1,
'title': 'ECCO'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Eyestar Optical'},
{   'description': [   '  Entrance not accessible',
'  Store interior not accessible',
'  Change room not very accessible',
'  Emergency exit'],
'stars': 0,
'title': 'Bonlook'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'FlyZone'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fonelab repair '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Gap'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Garage'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'GEOX '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Guess'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'H&M '},
{   'description': [   '  Entrance not accessible',
'  Store interior not accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 1,
'title': 'Hot Topic '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Hudson Bay '},
{   'description': [   '  Entrance not accessible',
'  Store interior not accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 1,
'title': 'International Clothiers '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Jack & Jones'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Journeys '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Jump+ '},
{   'description': [   '  Entrance not accessible',
'  Store interior not accessible',
'  Emergency exit'],
'stars': 0,
'title': 'JUST COZY'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Justice'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'La Senza'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Laura '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Le Chateau'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'LensCrafters'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Little Burgudy'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'lululemon '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'M Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'MAC Cosmetics '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 4,
'title': 'Michael Kors '},
{   'description': [   '  Entrance not accessible',
'  Store interior not very accessible',
'  Emergency exit'],
'stars': 2,
'title': 'MINISO'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'MUJI'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'MUJOSH'},
{   'description': [   '  Entrance accessible',
'  Store interior not very accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Naturalizer '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Nike'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Nutrition House '},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 3,
'title': 'NYX'},
{   'description': [   '  Entrance not accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 3,
'title': 'Obsessions '},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Old Navy'},
{   'description': [   '  Entrance accessible',
'  Store interior not very accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Pandora'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Pearle Vision'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 3,
'title': 'Peoples Jewels'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'PINK'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Reitmans '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Roots'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'RUDSAK'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'S & H Health Foods'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Saje'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Sephora '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Shoppers Drug Mart '},
{   'description': [   '  Entrance accessible',
'  Store interior not very accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Showcase'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Sirens '},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Sketchers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'SoftMoc '},
{   'description': [   '  Entrance not accessible',
'  Store interior not very accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Spencers Gifts'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Steve Madden'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'SUKOSHI'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Sunglass Hut'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Sunrise Records'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Suzy Shier'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Swarovski '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'TAN MUJIANG '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Tbooth Wireless'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Body Shop'},
{   'description': [   '  Entrance accessible',
'  Store interior not very accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'The Childrenâ\x80\x99s Place'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Source'},
{   'description': [   '  Entrance not accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'TORRID'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Toys Toys Toys'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Urban Behaviour'},
{   'description': [   '  Entrance not accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Urban Planet'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Vans'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Victoriaâ\x80\x99s Secret'},
{   'description': [   '  Entrance not very accessible',
'  Store interior mostly accessible',
'  Change room mostly accessible',
' Emergency exit'],
'stars': 2,
'title': 'Walmart '},
{   'description': [   '  Entrance not accessible',
'  Store interior not very accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'West 49'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Yves Rocher'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'ZARA '},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Zumiez'}]
