const data = [   
{   'description': [   ' Entrance accessible ',
' Store interior somewhat accessible',
' Emergency exit'],
'stars': 3,
'title': 'Accents'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Aldo'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Aldo Accessories'},
{   'description': [   ' Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Alex and Ani'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'American Eagle'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Ann Taylor'},
{   'description': [   ' Entrance accessible',
'  Store interior barely accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Anna Bella'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Apple'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Ardene'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Aritzia'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Armand Jewellers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Armani Exchange'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Aroma'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': "Arvinda's"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': "Auntie Anne's Pretzels"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Aveda'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'B2 Shoes'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Babaton'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Bake Three Fifty'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Banana Republic'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Bank of Montreal'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': "Barber's Chair"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Baskin Robbins'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bath & Body Works'},
{   'description': [   '  Entrance accessible',
'  Store interior  accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bell'},
{   'description': [   '  Entrance accessible',
'  Store interior  accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'Bell Kiosk'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Ben Sherman'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Bentley'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Best Buy Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit',
' Change room accessible'],
'stars': 3,
'title': 'Bikini Village'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Birks '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Bitter Sweet '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Blackjack BBQ'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Blackwell Supply Co.'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Change room not accessible',
' Emergency exit'],
'stars': 2,
'title': 'Bluenotes'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bonlook'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Booster Juice'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Boston Pizza'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Browns'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'BrÃ¸d'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Build-A-Bear'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bulk Barn'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Call it Spring'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Canada Post Office'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Canyon Creek Crophouse'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': "Carter's | OshKosh"},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Caryl Baker Visage'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Catalyst & Co'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Cellicon'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Champs'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Chatime'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Chatters Salon'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Emergency exit'],
'stars': 3,
'title': "Chico's"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Chocollata'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Chronic Ink'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'CIBC ATM'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Cineplex'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'City Shades'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': "Claire's"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Classic Fit Alterations'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Classic Fit Dry Cleaners'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Cleo'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Club Monaco'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Coach'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 4,
'title': 'COS'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Crate and Barrel'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'CrÃªpe de Licious'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'CrystalizeIT'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Davidâ\x80\x99s Tea'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Deciem'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Delta Optical'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'DHL Express'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Disney'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Dollarama'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Donato Salon + Spa'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Dynamite'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Earlâ\x80\x99s Kitchen + Bar'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'EB Games'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Ecco Shoes'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'European Jewellry'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Evaâ\x80\x99s Original Chimneys'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Ever New'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Eyestar Optical'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Fairweather'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fido'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fiorio'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Flight Centre'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Foot Locker/House of Hoops'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Fossil'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Freedom Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Freshly Squeesed'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fuwa Fuwa'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Gap'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Garage'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Genesis'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Geox'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'GNC'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Godiva'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Goodlife Fitness'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'GUESS'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'H&M'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'H&R Block'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Hakim Optical'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Hale Coffee'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Harry Rosen'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Hatley'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Hearing Solutions'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Holt Renfrew'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Honey'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Change room accessible',
'   Emergency exit'],
'stars': 2,
'title': 'Hot Topic'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Hudsonâ\x80\x99s Bay'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'ICE Currency Services'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Icing'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'IG Memories'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Indigo'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Indochino'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 2,
'title': 'International Clothiers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Jack & Jones'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': "Jack Astor's"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': "Jamie's Italian"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Jimmy The Greek'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Journeys'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Just Cozy'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Justice'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Kate Spade'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Kernels'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Kids Foot Locker/Fly Zone'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Kiehlâ\x80\x99s'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Koodo Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'La Carnita'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'La Mode Collection'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'La Senza'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'La Vie En Rose'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lacoste'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Laura'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Laura Secord'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'LCBO'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Le Chateau'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Le Chateau Menswear'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lense Crafters'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Leviâ\x80\x99s'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lids'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lindt Chocolate'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lâ\x80\x99intervalle'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Little Burgundy'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Lâ\x80\x99Occitane'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Loft'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Love Me Sweet'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Lucky Brand Jeans'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'Lucky Lotto Centre'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lululemon'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lush'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'M'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'MAC'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Magenta Photo Studio'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Marc Cain'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Maâ\x80\x99s Best Quality Soup'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Maska'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
' Emergency exit'],
'stars': 4,
'title': 'Massimo Dutti'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Matt & Nat'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Maverick Studio For Men'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Melanie Lyne'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Mendocino'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Michael Hill'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Michael Kors'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Microsoft'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'MidiCi'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Miniso'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Mobile Klinik'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Mobile Snap'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Morphe'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Mountain Warehouse'},
{   'description': [   '  Outside entrance accessible',
'  No button for inner entrance',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Moxieâ\x80\x99s'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Mr. Pretzels'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Muji'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Naturalizer'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Nature Collection'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Nespresso'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'New Steel'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Nike'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Nugateau'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Nutrition House'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'NYX'},
{   'description': [   ' Outisde entrance accessible',
' No button for inner entrance',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Okaidi'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Old Navy'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Ollie Quinn'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Octoberâ\x80\x99s Very Own'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Pandora'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Panera'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Pappa Roti'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Papyrus'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
' Kiosk'],
'stars': 5,
'title': 'Peloton'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Peopleâ\x80\x99s Jewellers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Perfume Shop'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Pierced'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Plus'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Point Zero'},
{   'description': [   '  No button on entrance',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Popeyes'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Pro Image'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Purdys Chocolatier'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'Rainbow Jade'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Real Fruit Bubble Tea'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Reds Wine Tavern'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Reitmans'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Richtree'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Rocky Mountain'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Rogers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Rolex Boutique | Raffi Jewellers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Roots'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Royal Bank ATM'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'RUDSAK'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'RW & Co.'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'S&H Health Foods'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Saje'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Salvatore Ferragamo'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Sansotei Ramen'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Scaddabush'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Scotiabank'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Second Cup'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Sephora'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Shoppers Drug Mart'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Showcase'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Simons'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Sketchers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Sleep Country'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'SoftMoc'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Soya & Kyo'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Spence Diamonds'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Sport Check'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Squish Candies'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Starbucks'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Steve Madden'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'StickerYou: The Pop Up'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Stich It'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Strauss Menâ\x80\x99s Wear'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Stuart Weitzman'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Sukoshi Mart'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Sunglass Hut'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Suzy'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Swarovski'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Swimco'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Szechuan Express'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Tbooth Wireless'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'TD'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Telus Mobility'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Ten Renâ\x80\x99s Tea'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Body Shop'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 2,
'title': 'The Childrenâ\x80\x99s Place'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Food District'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Rec Room'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Source'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'The Wine Shop & Tasting Room'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Tim Hortons'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'TONYC'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Topshop/Topman'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Torrid'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Tory Birch'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Town Shoes'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Toys Cubed'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Trade Secrets'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Travel currency Exchange'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Tripcentral'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Tsujiri'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Tumi'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Uniqlo'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit from lower level'],
'stars': 4,
'title': 'Urban Behaviour'},
{   'description': [   '  Entrance accessible',
'  Store interior barely accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Urban Kids'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Urban Outfitters'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Urban Planet'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Victoriaâ\x80\x99s Secret'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Victoriaâ\x80\x99s Secret Pink'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Virgin Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
' Kiosk'],
'stars': 5,
'title': 'Virgin Mobile Kiosk'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Walmart'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Watch It!'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'White House Black Market'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Whole Foods'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Wilfred'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Wireless + Kiosks'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Wirelesswave'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'WOW Mobile Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit',
'  Kiosk'],
'stars': 5,
'title': 'Yogen FrÃ¼z'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Yves Rocher'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Zara'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Zumiez'}]
