const data = [   
{   'description': [   ' Entrance accessible',
' Store interior not accessibility',
' Emergency exit'],
'stars': 2,
'title': 'Accents @ home'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Adiddas'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Aerie'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Emergency exit'],
'stars': 3,
'title': 'ALDO'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'American Eagle'},
{   'description': [   '  Entrance accessible',
'  Emergency exit',
'  Store interior partially accessible',
'  Change room not accessible'],
'stars': 3,
'title': 'Anna Bella'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Aritzia'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Aroma'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Asics'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': "Auntie Anne's Pretzels"},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bass Pro Shops'},
{   'description': [   '  Entrance accessible',
'  Store interior not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Bath & Body Works'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency Exit'],
'stars': 4,
'title': 'Babies R Us'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Bannana Republic'},
{   'description': [   '  Entrance accesible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Beauty Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bell'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Ben Sherman'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Below the Belt'},
{   'description': [   '  Entrance accessible',
'  Store interior not accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 2,
'title': 'Bench'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bentley'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Best Buy'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Bikini Village'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Blaze Pizza'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Blu'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bluenotes'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Boathouse'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Brooks Brothers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Bonlook'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Boss'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Browns'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Build-a-bear Workshop'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Calforex'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Call it Spring'},
{   'description': [   '  Entrance accessible',
'  Change room accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Calvin Klein'},
{   'description': [   '  Entrance accessible',
'  Store interior not accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': "Carter's | Osh Kosh B'gosh"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Caryl Baker Visage'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Cellicon'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Champs'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Cinnabon'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Charmed Aroma'},
{   'description': [   ' Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': "Claire's"},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Coach'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Cole Haan'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Crepe De Licious'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Crocs'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Danier'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Danish Pastry House'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'DAVIDsTEA'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Designer Depot'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Disney Store'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'DKNY'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Dr.Martens Outlet'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'DSW'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Dynamite'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'EB Games'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Ecco'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Eddie Bauer'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Eh Canada!'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': "Ela's Bakeshop"},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Ever New'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Eyestar Optical'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 2,
'title': 'Fairweather'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Famous Footwear'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 2,
'title': 'Fanatics'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Femme'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Fido'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Fiorio'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Flight Centre'},
{   'description': [   ' Entrance accessible',
' Food court accesible',
' Emergency exit'],
'stars': 5,
'title': 'Food Court'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Foot Locker'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 2,
'title': 'Foot Locker Kids'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Fossil'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Freedom Mobile'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Freshly Squeezed'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Frida Brow Bar'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Fruit of the Land'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Gap'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Garage'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'GBG'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Geox'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Globo Shoes'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'GNC'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Guess Accessories'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Guess'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Haggar'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Haight Ashbury'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'H&M'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room accessible',
' Emergency exit'],
'stars': 2,
'title': 'Hockey Life'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room accessible',
' Emergency exit'],
'stars': 2,
'title': 'Honey'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room accessible',
' Emergency exit'],
'stars': 1,
'title': 'Hot Topic'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'IHALO KRUNCH'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'INS Market'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 0,
'title': 'International Clothiers'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 3,
'title': 'International Kids'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'International News'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Jack & Jones'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 5,
'title': 'Janan'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'J Crew'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'JCY House Boutique'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Joe Fresh'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Johnston & Murphy'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Journeys'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Jugo Juice'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Jump +'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Justice'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Kate Spade'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Kenneth Cole'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Kernels and Baskin Robbins'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Koodo'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lacoste'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'La Senza'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 4,
'title': 'LAUFT'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Laura'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'La Vie en Rose'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Some activities are accessible',
' Emergency exit'],
'stars': 3,
'title': 'Legoland'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 2,
'title': 'Le ChÃ¢teau'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lenscrafters'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': "Levi's"},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Lids'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lily Jewels'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lindt'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lionesse'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Little Burgundy'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'LS-Leather'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lucky Brand'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lululemon'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Luxury Eyewear'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'MAC'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Mad Radish'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Make it Fit Alterations'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Marc Cain'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Matt & Nat'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'M Boutique'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Melanie Lyne'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Michael Hill'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Michael Kors'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Miniso'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Mobile Klinki'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Mobile Outfitters'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Moments'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Motherhood Maternity'},
{   'description': [   ' Entrance accessible',
' Store interior not accessibility',
' Change room accessible',
' Emergency exit'],
'stars': 2,
'title': 'Mountain Warehouse'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Naturalizer'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Nature Collection'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Nespresso'},
{   'description': [   ' Entrance accessible',
' Parts of store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'New Steel'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Nike'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Nordstrom Rack'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Oakley'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Outdoor World'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Occhiali Eyewear'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Old Navy'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Panda'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Pandora'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Peoples'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Pickle Barrel'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Polo Ralph Lauren'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Pretty Young Thing'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Puma'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': "Purdy's"},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Quilts etc Home'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Radiant'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Real Fruit'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Reebok'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Refeul Juicery'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 2,
'title': "Ricki's"},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Rocky Mountain'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Rogers'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Roots'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Royal Doulton'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Rudsak'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'RW&co.'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Saje'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Saks Fifth Avenue'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Sephora'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Shoppers Drug Mart'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 4,
'title': 'Showcase'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Signature perfumes'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Showcase'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Squish'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Starbucks'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Steve Madden'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Soft Moc'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Sport Check Kids'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Sticker You'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Studio C Minerals'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 3,
'title': 'Sugar Mountain'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Sunglass Hut'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 1,
'title': 'Suzy Shier'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Swarovski'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Sweetie Petwear'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Emergency exit'],
'stars': 2,
'title': 'Szechuan Szechuan'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Emergency exit'],
'stars': 5,
'title': 'T booth wirless'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Telus'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'The Body Shop'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': "The Children's Place"},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room accessible',
' Emergency exit'],
'stars': 2,
'title': 'The North Face'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 4,
'title': 'The Outlet Harry Rosen'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'The Shoe Company'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'The Source'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Tim Hortons'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Tommy Bahama'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Tommy Hilfiger'},
{   'description': [   ' Entrance accessible',
' Store interior not accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 2,
'title': 'Torrid'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Toys R us'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'TOYS TOYS TOYS'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Trade Secrets'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Triumph'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'True Religion'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'TUMI'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Ugg'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Under Armour'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'UNIQLO'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Urban Kids'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Urban Planet'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Van Heusen'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Vans'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room accessible',
' Emergency exit'],
'stars': 5,
'title': "Victoria's Secret"},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Villa Madina'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Virgin Mobile'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Virtual Sting'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 4,
'title': 'Walking on a Cloud'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Watch it!'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Watch Station'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'White Barn'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Winners'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'Wirelesswave'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'WLKN'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'WOW!'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room not accessible',
' Emergency exit'],
'stars': 2,
'title': 'Ya Ya & Co.'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Zumiez'},
{   'description': [   ' Entrance accessible',
' Store interior partially accessible',
' Emergency exit'],
'stars': 3,
'title': 'ZWILLING J.A HENCKLES'}]
