const data = [   
{   'description': [   ' Entrance accessible ',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'BMO'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Store is small',
'  Emergency exit'],
'stars': 4,
'title': 'Canada Post'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'CIBC'},
{   'description': [   ' Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Currency Mart'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Narrow aisles'],
'stars': 4,
'title': 'Dollarama'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Store is small with  little open space'],
'stars': 4,
'title': 'Fido'},
{   'description': [' Entrance accessible', '  Store interior accessible'],
'stars': 5,
'title': 'Forest Nail and Spa'},
{   'description': ['  Entrance accessible', '  Store interior accessible'],
'stars': 5,
'title': 'Fuzz Wax Bar'},
{   'description': [   '  Entrance accessible',
'  Store interior  mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'GNC'},
{   'description': [   ' (3.5)',
'  Entrance accessible',
'  Facility interior mostly accessible',
' Changes rooms accessible',
'  Emergency exit'],
'stars': 3,
'title': 'LA Fitness'},
{   'description': [   '  Entrance accessible',
'  Store interior  mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': "Longo's"},
{   'description': ['  Entrance accessible', '  Store interior accessible'],
'stars': 5,
'title': 'Meridian'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible'],
'stars': 4,
'title': "Oshkosh | Carter's"},
{   'description': ['  Entrance accessible', '  Store interior accessible'],
'stars': 5,
'title': "Reitman's"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible'],
'stars': 4,
'title': "Ricki's"},
{   'description': ['  Entrance accessible', '  Store interior accessible'],
'stars': 5,
'title': 'Shoppers Drug Mart'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'TD canada Trust'},
{   'description': ['  Entrance accessible', '  Store interior accessible'],
'stars': 5,
'title': 'Tonino'},
{   'description': ['  Entrance accessible', '  Store interior accessible'],
'stars': 5,
'title': 'Vaule Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Winners'},
{   'description': ['  Entrance accessible', '  Store interior accessible'],
'stars': 5,
'title': 'Yonge and Sheppard Centre Dentistry'}]
