const data = [   
{   'description': [   ' Entrance accessible ',
' Store interior accessible',
' Change room not accessible',
' No emergency exit'],
'stars': 4,
'title': 'Addition Elle'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Angel Cleaners'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Altima Dental'},
{   'description': [   ' Store interior accessible',
' No change room service',
' No emergency exit'],
'stars': 4,
'title': 'Beauty First'},
{   'description': [' Store interior accessible', ' No emergency exit'],
'stars': 4,
'title': 'Bentley'},
{   'description': [   '  Entrance not accessible',
'  Store interior not accessible',
'  No emergency exit'],
'stars': 0,
'title': 'Body Shop'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Buck or Two'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Change room not accessible',
' No emergency exit'],
'stars': 4,
'title': "Carter's Babies and Kids / Oshkosh B' Gosh"},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Cineplex'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': "Dal Moro's"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Fido'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Freedom Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
'  No emergency exit'],
'stars': 3,
'title': 'Good Life'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Holika Holika'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'HSBC'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Indigo'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Koodo'},
{   'description': [   '  Entrance accessible',
'  Store interior partially accessible',
'  No emergency exit'],
'stars': 3,
'title': 'La Vie en Rose'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'LCBO'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Lotto Station'},
{'description': [], 'stars': 0, 'title': 'M Boutique'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Metro'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Michael Hill'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Nails For You'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Nutrition Village'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Optika'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Papyrus'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Ray Daniels Salon and Spa'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Reitmans'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  No emergency exit'],
'stars': 3,
'title': 'Rexall'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Shoppers'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Swarovskii'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'TD'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Telus'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'The Source'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'The Tea Shop'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Tight'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Toys R Us / Babies R Us'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  No emergency exit on lower level',
'  Elevator in store'],
'stars': 3,
'title': 'Urban Outfitters'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Value Mobile'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': 'Value Village'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Walking on a Cloud'},
{   'description': [   ' Store interior partially accessible',
' No emergency exit'],
'stars': 3,
'title': 'Winners'},
{   'description': ['  Store interior accessible', '  Emergency exit'],
'stars': 5,
'title': 'Y & E Variety'},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' No emergency exit'],
'stars': 4,
'title': '60 Minutes Photo Lab'}]
