const data = [   
{   'description': [   ' Entrance accessible ',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Aldo'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Narrow hallways',
' Emergency exit'],
'stars': 4,
'title': 'Aldo Accessories '},
{   'description': [   ' Entrance accessible',
' Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Alex and Ani'},
{   'description': [   ' Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'AllSaints'},
{   'description': [   ' Entrance accessible',
' Store interior mostly accessible',
' Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'American Eagle Outfitters'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Ann Taylor'},
{   'description': [   ' Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Apple'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': "ARC'TERYX"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Aritzia'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Atelier Cologne'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Aveda Experience Centre'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'B2'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible with some '
'narrow corners',
'  Emergency exit'],
'stars': 4,
'title': 'Babaton'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Balenciaga'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room somewhat narrow',
'  Emergency exit'],
'stars': 4,
'title': 'Banana republic'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bath and Body Works'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Bell'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Bikini village'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Birks'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Bose'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'BOSS'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Bottega Veneta'},
{   'description': [   '  Entrance narrow',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Breitling'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Browns'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Burberry'},
{   'description': [   '  Entrance narrow',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'BVLGARI'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Call It Spring'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Canada Goose'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Cartier'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Casper'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Champs Sports'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Chanel at Holt Renfrew'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Chloe'},
{   'description': [   '  Entrance narrow',
'  Store interior mostly accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Club Monaco Men'},
{   'description': [   '  Entrance narrow',
'  Store interior mostly accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Club Monaco Women'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Coach'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Continental Currency Exchange'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'COS'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Crate & Barrel'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'David Yurman'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'DAVIDsTEA'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Diesel'},
{   'description': [   '  Entrance narrow',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Disney'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Donato Salon + Spa'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Dynamite'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Dyson Demo'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
' Emergency exit'],
'stars': 4,
'title': 'EB Games'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Ecco Shoes'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'European Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Fairweather'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Fido'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Foot Locker'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Footaction'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Fossil'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Freedom Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'FURLA'},
{   'description': [   '  Entrance narrow',
'  Store interior accessible',
'  Change room somewhat accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Gap Kids/Baby'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'GARAGE'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'GEOX'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Godiva Chocolatier'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Gucci at Holt Renfrew'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Guess'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Guess by Marciano'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'H&M'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Harry Rosen'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Holt Renfrew'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'honey'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Hublot '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Hunter'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Indigo Books'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'INDOCHINO'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Innisfree'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'iQ'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'IWC Schaffhausen'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'J. Crew'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Jack & Jones'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Jaeger LeCoultre'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Jimmy Choo'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'John Varvatos'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Johnston & Murphy'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Journeys'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible ',
'  Emergency exit'],
'stars': 4,
'title': 'Kate Spade New York'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Emergency exit'],
'stars': 5,
'title': 'Kids Foot Locker & Fly Zone'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'KITKAT Chocolatory '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Koodo'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'La Senza'},
{   'description': [   '  Entrance not accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Lacoste'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Lindt Chocolate Shop'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Emergency exit'],
'stars': 4,
'title': 'LadurÃ©e'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Laline'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  One accessible change room',
' Emergency exit'],
'stars': 3,
'title': 'Le ChÃ¢teau'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'The LEGO Store'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lenscrafters'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
'  Emergency exit'],
'stars': 4,
'title': 'Leviâ\x80\x99s'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Emergency exit'],
'stars': 3,
'title': 'Lids'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Links of London'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Lâ\x80\x99OCCITANE en Provence'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'LOFT'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Longchamp'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Lululemon Athletica'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'LUSH'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 5,
'title': 'M.A.C Cosmetics'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'M Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Mackage'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Maje'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Massimo Dutti'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Melanie Lyne'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Michael Hill Jewellers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Micheal Kors'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Microsoft'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Miele'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Moncler'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Montblanc'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Moose Knuckles'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Mr & Mrs Italy'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'MUJI'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'MUJOSH'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Mulberry'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'NadÃ¨ge'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Nature Collection'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Nespresso'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Nike'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Elavators available',
' Emergency exit on first floor only'],
'stars': 5,
'title': 'Nordstrom'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Nutrition House'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'NYX Professional Makeup'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'OAK + FORT'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Octoberâ\x80\x99s Very Own'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
'  Elevator available',
' Emergency exit on first floor only'],
'stars': 3,
'title': 'Old Navy'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Oliver Peoples'},
{   'description': [   '  Entrance narrow',
'  Store interior accessible',
' Emergency exit'],
'stars': 4,
'title': 'Omega - Inside European Boutique'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Pandora'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Panerai'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Papyrus'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Peloton inside Concept'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': "People's Jewellers"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Piaget'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Plus'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Elevator available',
' Emergency exit on first floor only'],
'stars': 4,
'title': 'Pottery Barn'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Prada at Holt Renfrew'},
{   'description': [   '  Entrance narrow',
'  Store interior accessible',
' Emergency exit'],
'stars': 4,
'title': 'Raffi Jewellers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Reformation'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Rogers'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Roots'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'RUDSAK'},
{   'description': [   '  Entrance very narrow',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 3,
'title': 'SAINT LAURENT'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Saje Natural Wellness'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Salvatore Ferragamo'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Samsung'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Sandro'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Scotiabank'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Sephora'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible; somewhat '
'crowded',
' Emergency exit'],
'stars': 4,
'title': 'Shoppers Drug Mart'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Sketchers'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'SoftMoc'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Elevator available',
' Emergency exit'],
'stars': 3,
'title': 'Sport Chek'},
{   'description': [   '  Entrance a bit narrow',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Steve Madden'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Stitch It Clothing Alterations'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Stuart Weitzman'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Sunglass Hut'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'TAG Heuer'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'Ted Baker London '},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Telus'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': "Ten Ren's Tea"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Tesla Motors'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit on first floor only'],
'stars': 5,
'title': 'Hudsonâ\x80\x99s Bay'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'The Body Shop'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
' Emergency exit'],
'stars': 3,
'title': 'The Source'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 3,
'title': 'Thyme Maternity'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Tiffany & Co.'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Tim Hortons'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
' Emergency exit'],
'stars': 4,
'title': "Topshop - Inside Hudson's Bay"},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Tory Burch'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Tristan'},
{   'description': [   '  Entrance a bit narrow',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'True Religion Brand Jeans'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'TUMI'},
{   'description': [   '  Entrance narrow',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'UGG Australia'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 5,
'title': 'UNIQLO'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'UNTUCKit'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
'  Elevator available',
' Emergency exit'],
'stars': 4,
'title': 'Urban Behavior'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Vacheron Constantin'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Valentino'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Van Cleef & Arpels'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 4,
'title': 'Vans'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Versace'},
{   'description': [   '  Entrance accessible',
'  Store interior somewhat accessible',
'  Change room not accessible',
' Emergency exit'],
'stars': 3,
'title': 'Victoriaâ\x80\x99s secret'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Village Juicery'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Virgin Mobile'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Walk & Wear Fine Shoe Repair'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Warby Parker'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'White House | Black Market'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
'  Change room not accessible',
' Emergency exit'],
'stars': 4,
'title': 'Wilfred'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'WIRELESSWAVE'},
{   'description': [   '  Entrance accessible',
'  Store interior accessible',
' Emergency exit'],
'stars': 5,
'title': 'Zadig & Voltaire'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
'  Change room accessible',
' Emergency exit'],
'stars': 4,
'title': 'Zara'},
{   'description': [   '  Entrance accessible',
'  Store interior mostly accessible',
' Emergency exit'],
'stars': 3,
'title': 'Zara Home'}]
